lb:
  extends:
    file: common.yml
    service: lb
  links:
    - dockerapp

dockerapp:
  extends:
    file: common.yml
    service: dockerapp
  build: . 
  links:
    - redis

redis:
  extends:
    file: common.yml
    service: redis
